server:
  port: 1004
  servlet:
    context-path: /customer-service

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/